Repository softeer5th/Team5-EQUUS-N, pull requests merged in 2025-02, with the labels that each got.

#40 [FD-32] 요청 받은 수시 피드백 조회
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#41 [FD-247] 수시 피드백 요청 인자를 팀 이름에서 팀 id로 변경
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#42 [FD-241] 팀장 정보 팀 도메인으로 이동
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamRole.java
Labels: BE, refactor

#43 [FD-245] 회고 조회 인자 팀 id로 변경
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java
Labels: BE, feat

#44 [FD-235] 세션 조회용 ArgumentResolver 생성
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/WebConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthExceptionHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/LoginStateRequiredException.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/AuthInterceptor.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/Login.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/LoginMemberArgumentResolver.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/infra/AuthInterceptorTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/infra/LoginMemberArgumentResolverTest.java
Labels: BE, feat

#45 [FD-242] 객관식 피드백 재구성
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackCategory.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackFeeling.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/ObjectiveFeedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#46 [FD-105] 피드백 좋아요/취소
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FeedbackLikedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#47 [FD-11] 회원 정보 조회 기능 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/mapper/MemberMapper.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/FindControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/MemberDto.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/ProfileImage.java
  back-end/src/main/java/com/feedhanjum/back_end/member/service/MemberService.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java
Labels: BE, feat

#51 [FD-35] 정기 피드백 전송
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/RegularFeedbackCreatedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/NoRegularFeedbackRequestException.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/RegularFeedbackRequestRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleMemberRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#49 [FD-8] 회원 활동명 변경 구현
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/InternalErrorControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/member/service/MemberService.java
  back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/member/domain/MemberTest.java
  back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java
Labels: BE, feat

#50 [FD-249] 프로필 이미지 수정
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java
Labels: BE, feat

#52 [FD-34] 정기 피드백 요청 생성
  back-end/src/main/java/com/feedhanjum/back_end/event/config/EventConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/RegularFeedbackRequestCreatedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/ScheduleEndEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/handler/ScheduleEndEventListener.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#53 [FD-74] 정기 피드백 건너뛰기
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/RegularFeedbackRequestRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#54 [FD-234] 일정별 정기 피드백 요청 조회
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#55 [FD-73] 수시 피드백 요청 모두 거절
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#57 [FD-254] 불필요한 양방향 연관관계 제거
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
Labels: BE, refactor

#58 [FD-13] 팀 생성 기능 추가
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamCreateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/dto/TeamCreateDto.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#59 [FD-14] 내가 속한 팀 조회 기능 구현
  back-end/src/main/java/com/feedhanjum/back_end/core/config/QuerydslConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#60 [FD-21] 팀원 조회 기능 구현
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/member/repository/MemberQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/member/service/MemberService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamDetailResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamMemberControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamMembershipNotFoundException.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
Labels: BE, feat

#61 [FD-33] 받은 피드백 조회
  back-end/src/main/java/com/feedhanjum/back_end/core/config/QuerydslConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/ReceivedFeedbackDto.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryServiceTest.java
Labels: BE, feat

#62 [FD-99] 보낸 피드백 조회
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/SentFeedbackDto.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryServiceTest.java
Labels: BE, feat

#56 [FD-195] 모달, 노티피케이션 컴포넌트 개발
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App2.jsx
  front-end/src/assets/lotties/box.json
  front-end/src/assets/lotties/file.json
  front-end/src/assets/lotties/letter.json
  front-end/src/components/Icon.jsx
  front-end/src/components/modals/Modal.jsx
  front-end/src/components/modals/ModalBase.jsx
  front-end/src/main.jsx
  front-end/src/pages/main/components/Notification.jsx
  front-end/src/utility/handleModal.js
Labels: FE, feat

#63 [FD-22] 팀원 제거 구현
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#64 [FD-17] 팀장 권한 위임 구현
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamLeaderMustExistException.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamMemberControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/domain/TeamTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#65 [FD-19] 팀 탈퇴 구현
  back-end/src/main/java/com/feedhanjum/back_end/member/repository/MemberQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#66 [FD-253] 수시 피드백 작성 시 수시 피드백 요청에서 삭제
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/handler/FrequentFeedbackCreatedEventHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#68 [FD-232] byte 길이 validator 구현
  back-end/src/main/java/com/feedhanjum/back_end/core/constraints/ByteLength.java
  back-end/src/main/java/com/feedhanjum/back_end/core/constraints/ByteLengthValidator.java
  back-end/src/test/java/com/feedhanjum/back_end/core/constraints/ByteLengthValidatorTest.java
Labels: BE, feat

#70 [FD-261] feat: 레이아웃 및 라우팅 세팅
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/Layout.jsx
  front-end/src/main.jsx
Labels: FE, feat

#75 [FD-196] 드롭다운, 텍스트영역 컴포넌트 개발
  front-end/src/App.jsx
  front-end/src/components/Dropdown.jsx
  front-end/src/components/NavBar2.jsx
  front-end/src/components/TextArea.jsx
  front-end/src/pages/feedback/FeedbackRequest.jsx
  front-end/src/utility/inputChecker.js
Labels: FE, feat

#77 [FD-26] 일정 생성 구현
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/ScheduleController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleCreateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleRole.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Todo.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleAlreadyExistException.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleRequestDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleResponseDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/TodoListDto.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/controller/ScheduleControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/service/ScheduleServiceTest.java
Labels: BE, feat

#76 [FD-246] 피드백 관련 컨트롤러 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/Login.java
  back-end/src/main/java/com/feedhanjum/back_end/core/dto/Paged.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/InternalErrorControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FrequentFeedbackRequestForApiRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FrequentFeedbackRequestQueryRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FrequentFeedbackSendRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/ReceivedFeedbacksQueryRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/RegularFeedbackRequestQueryRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/RegularFeedbackSendRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/SentFeedbacksQueryRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FrequentFeedbackRequestDto.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/RegularFeedbackRequestDto.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackFeeling.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/ObjectiveFeedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/FeedbackControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/NoRegularFeedbackRequestException.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/ScheduleAlreadyExistException.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/ScheduleControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/ReceivedFeedbackDto.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/SentFeedbackDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/RegularFeedbackRequestQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestQueryRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/resources/application-test.yml
Labels: BE, feat

#80 [FD-273] ec2 배포 GitHub action 생성
  .github/workflows/ec2-deploy.yml
  .github/workflows/gradle-test.yml
Labels: BE, feat

#83 [FD-191] 메인카드 컴포넌트 개발
  front-end/src/App2.jsx
  front-end/src/components/modals/Modal.jsx
  front-end/src/components/modals/ModalBase.jsx
  front-end/src/pages/feedback/FeedbackRequest.jsx
  front-end/src/pages/main/components/MainCard.jsx
Labels: FE, feat

#79 [FD-268] 이메일 api 컨트롤러 생성
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/PasswordResetEmailSendRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/PasswordResetEmailSendResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/PasswordResetEmailVerifyRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/SignupEmailSendRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/SignupEmailSendResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/SignupEmailVerifyRequest.java
Labels: BE, feat

#81 [FD-271] 앱 내부 알림함 api 컨트롤러 생성
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/NotificationController.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/NotificationType.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/UnreadNotificationResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/FeedbackReceiveNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/FeedbackReportCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/FrequentFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/HeartReactionNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/InAppNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/RegularFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/ScheduleCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/TeamLeaderChangeNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/dto/notification/UnreadFeedbackExistNotificationDto.java
Labels: BE, feat

#84 [FD-274] ai 다듬기 api 컨트롤러 생성
  .github/workflows/ec2-deploy.yml
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackRefinementController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FeedbackRefineRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FeedbackRefineResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/RefineRemainCountResponse.java
Labels: BE, feat

#78 [FD-29] 일정 수정 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/core/config/ClockConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/ScheduleControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/ScheduleController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleCreateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleAlreadyExistException.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleIsAlreadyEndException.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleMembershipNotFoundException.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleRequestDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/TodoListDto.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamCreateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamUpdateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/dto/TeamCreateDto.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/dto/TeamUpdateDto.java
  back-end/src/main/resources/application.yml
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/controller/ScheduleControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/domain/ScheduleTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/service/ScheduleServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#89 [FD-186] 메인 페이지 중간 pr
  front-end/package.json
  front-end/src/App.jsx
  front-end/src/components/Accordion.jsx
  front-end/src/components/MainCard2.jsx
  front-end/src/components/buttons/TextButton.jsx
  front-end/src/pages/feedback/FeedbackRequest.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/main/components/MainCard.jsx
Labels: FE, feat

#92 [FD-207] 일정확인화면 개발
  front-end/src/App.jsx
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/CalendarParts.jsx
  front-end/src/pages/calendar/components/CalendarWeeks.jsx
  front-end/src/pages/calendar/components/ScheduleCard.jsx
  front-end/src/utility/time.js
Labels: FE, feat

#97 [FD-264, FD-265, FD-28] 일정 조회
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/ScheduleController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleBetweenDurationRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/dto/ScheduleProjectionDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleMemberNestedDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleNestedDto.java
Labels: BE, feat

#98 [FD-292] 일정 관련 버그 수정
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/InternalErrorControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/member/repository/MemberQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/dto/ScheduleProjectionDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamMemberControllerAdvice.java
Labels: BE, fix

#86 [FD-259] 회고에 제목 추가
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java
Labels: BE, feat

#88 [FD-275] 회고 관련 컨트롤러 구현
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/RetrospectController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/RetrospectWriteRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/RetrospectsQueryRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FrequentFeedbackRequestForApiResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/RegularFeedbackRequestForApiResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/RetrospectResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/RetrospectQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/RetrospectControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java
Labels: BE, feat

#91 [FD-284] 알림 도메인 생성
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/NotificationController.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/UnreadNotificationResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FeedbackReceiveNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FeedbackReportCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FrequentFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/HeartReactionNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/InAppNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/RegularFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/ScheduleCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/TeamLeaderChangeNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/UnreadFeedbackExistNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FeedbackReceiveNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FeedbackReportCreateNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FrequentFeedbackRequestNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/HeartReactionNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/InAppNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/NotificationType.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/RegularFeedbackRequestNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/ScheduleCreateNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/TeamLeaderChangeNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/UnreadFeedbackExistNotification.java
Labels: BE, feat

#105 [FD-297] 팀,회원,일정 도메인에 대한 swagger api 기능문서 작성
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/ProfileChangeRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/member/service/MemberService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/ScheduleController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/exception/ScheduleControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamQueryRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/member/controller/MemberControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/member/service/MemberServiceTest.java
Labels: BE, feat

#96 [FD-272] 여러 알림 일괄 읽기
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/InAppNotificationController.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/MultipleNotificationReadRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FeedbackReceiveNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FeedbackReportCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FrequentFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/HeartReactionNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/InAppNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/RegularFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/ScheduleCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/TeamLeaderChangeNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/UnreadFeedbackExistNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/InAppNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/RegularFeedbackRequestNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/controller/InAppNotificationControllerTest.java
Labels: BE, feat

#100 [FD-295] 이메일 발송 인프라 작업
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/EmailService.java
  back-end/src/main/resources/application.yml
Labels: BE, feat

#101 [FD-40, 266] 회원가입 인증 이메일 전송
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/SignupEmailVerifyRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/SignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/SignupTokenNotValidException.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/SignupTokenVerifyRequiredException.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/SessionConst.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/EmailService.java
  back-end/src/main/resources/application-dev.yml
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
Labels: BE, feat

#106 [FD-208] 일정추가수정 화면 개발
  front-end/src/api/useAuth.js
  front-end/src/api/useCalendar.js
  front-end/src/components/Accordion.jsx
  front-end/src/components/CustomDatePicker.jsx
  front-end/src/components/CustomInput.jsx
  front-end/src/components/Dropdown.jsx
  front-end/src/components/buttons/LargeButton.jsx
  front-end/src/components/buttons/MediumButton.jsx
  front-end/src/components/toasts/Toast.jsx
  front-end/src/customDatePicker.css
  front-end/src/mocks/browser.js
  front-end/src/mocks/handlers2.js
  front-end/src/mocks/mockData2.js
  front-end/src/pages/auth/SignIn.jsx
  front-end/src/pages/auth/SignUp.jsx
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
  front-end/src/pages/calendar/components/ScheduleCard.jsx
  front-end/src/pages/calendar/components/ScheduleDeleteModal.jsx
  front-end/src/pages/calendar/components/TimeSelector.jsx
  front-end/src/pages/calendar/components/Todo.jsx
  front-end/src/pages/teamspace/TeamSpaceMake.jsx
  front-end/src/utility/inputChecker.js
  front-end/src/utility/time.js
Labels: FE, feat

#107 [FD-214] 보낸받은 피드백 화면 개발
  front-end/src/App.jsx
  front-end/src/api/useFeedback.js
  front-end/src/components/NavBar2.jsx
  front-end/src/mocks/handlers2.js
  front-end/src/mocks/mockData2.js
  front-end/src/pages/feedback/FeedbackReceived.jsx
  front-end/src/pages/feedback/FeedbackSent.jsx
  front-end/src/pages/feedback/components/FeedBack.jsx
Labels: FE, feat

#108 [FD-205] 알림함화면 개발
  front-end/src/App.jsx
  front-end/src/assets/images/pray.png
  front-end/src/main.jsx
  front-end/src/mocks/mockData.js
  front-end/src/pages/main/NotificationPage.jsx
  front-end/src/pages/main/components/Alarm.jsx
  front-end/src/utility/time.js
Labels: FE, feat

#110 [FD-305] DTO 스키마 Swagger 문서 작성
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/ProfileChangeRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleBetweenDurationRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/dto/ScheduleProjectionDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleMemberNestedDto.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/dto/ScheduleNestedDto.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamCreateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamDetailResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamUpdateRequest.java
Labels: documentation, BE

#112 [FD-309] refactor: url parameter를 base api에서 처리할 수 있도록
  front-end/src/api/baseApi.js
Labels: FE, refactor

#109 [FD-304] 팀에 팀 멤버 추가
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FrequentFeedbackRequestForApiResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FrequentFeedbackRequestNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/event/handler/FrequentFeedbackRequestCreatedHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/FrequentFeedbackRequestCreatedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/FrequentFeedbackRequestedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/TeamMemberLeftEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/handler/TeamMemberLeftHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamMemberRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/domain/TeamTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/util/DomainTestUtils.java
  back-end/src/test/java/com/feedhanjum/back_end/util/SessionTestUtil.java
Labels: BE, feat

#111 [FD-302] 팀 가입 토큰 생성
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamJoinTokenResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamJoinToken.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamJoinTokenRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
Labels: BE, feat

#115 [FD-307] 팀스페이스 관리 화면 개발 1
  front-end/src/App.jsx
  front-end/src/api/useAuth.js
  front-end/src/api/useCalendar.js
  front-end/src/api/useFeedback.js
  front-end/src/api/useTeamspace.js
  front-end/src/components/Accordion.jsx
  front-end/src/mocks/handlers2.js
  front-end/src/mocks/mockData2.js
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/teamspace/TeamSpaceList.jsx
  front-end/src/pages/teamspace/components/TeamElement.jsx
Labels: FE, feat

#117 [FD-250] 사용자별 피드백 선호도 자료구조 생성
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/FeedbackPreference.java
  back-end/src/test/java/com/feedhanjum/back_end/member/domain/FeedbackPreferenceTest.java
Labels: BE, feat

#120 [FD-206] 홈에서 일정 역할 추가 화면 개발
  front-end/src/api/useFeedback.js
  front-end/src/pages/calendar/components/TodoAdd.jsx
  front-end/src/pages/feedback/components/FeedBack.jsx
  front-end/src/pages/main/MainPage.jsx
Labels: FE, feat

#121 [FD-217] 회고화면 개발
  front-end/src/App.jsx
  front-end/src/api/useMyPage.js
  front-end/src/mocks/handlers2.js
  front-end/src/mocks/mockData2.js
  front-end/src/pages/feedback/components/FeedBack.jsx
  front-end/src/pages/mypage/SelfFeedback.jsx
Labels: FE, feat

#124 [FD-313] 전역상태 추가
  front-end/src/App.jsx
  front-end/src/TeamContext.jsx
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/useTeam.jsx
Labels: FE, feat

#125 [FD-186] feat: 메인페이지에 전역상태 반영 및 바텀시트 연결
  front-end/src/api/useAuth.js
  front-end/src/api/useMainPage.js
  front-end/src/components/Accordion.jsx
  front-end/src/mocks/handlers.js
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/main/components/MainCard.jsx
  front-end/src/pages/teamspace/TeamSpaceList.jsx
  front-end/src/useTeam.jsx
  front-end/src/utility/time.js
Labels: FE, refactor

#118 [FD-86, FD-38] 푸시 알림 구독 및 발송
  back-end/.gitignore
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/notification/config/WebPushConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/config/WebPushProperty.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/WebPushNotificationController.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/ApplicationServerKeyResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/SubscribePushNotificationRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/WebPushSubscription.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/event/handler/InAppNotificationCreatedHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/WebPushSubscriptionRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/WebPushService.java
  back-end/src/main/resources/application-dev.yml
  back-end/src/main/resources/application.yml
  back-end/src/test/java/com/feedhanjum/back_end/BackEndApplicationTests.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/test/config/MailMockConfig.java
  back-end/src/test/java/com/feedhanjum/back_end/test/config/PushMockConfig.java
  back-end/src/test/java/com/feedhanjum/back_end/test/util/DomainTestUtils.java
  back-end/src/test/java/com/feedhanjum/back_end/test/util/SessionTestUtil.java
  back-end/src/test/resources/application-test.yml
Labels: BE, feat

#123 [FD-224] 도메인 주소 설정 및 https 적용
  back-end/.gitignore
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/WebConfig.java
  back-end/src/test/resources/application-test.yml
Labels: BE, chore

#126 [FD-312] feat: 피드백 선호도 조회 스키마 변경
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/MemberFeedbackPreferenceDto.java
Labels: BE, feat

#127 [FD-316] feat: 키 생성 전략 IDENTITY로 변경
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/InAppNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
Labels: BE, feat

#130 [FD-207] 일정화면 추가 개발
  front-end/src/api/useCalendar.js
  front-end/src/api/useTeamspace.js
  front-end/src/mocks/mockData2.js
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/CalendarParts.jsx
  front-end/src/pages/calendar/components/CalendarWeeks.jsx
  front-end/src/pages/calendar/components/ScheduleCard.jsx
  front-end/src/pages/calendar/hooks/useCalendarScroll.jsx
  front-end/src/pages/calendar/hooks/useSchedule.jsx
  front-end/src/pages/calendar/hooks/useScheduleAction.jsx
  front-end/src/pages/teamspace/TeamSpaceManage.jsx
  front-end/src/utility/time.js
Labels: FE, fix, refactor

#128 [FD-43] 일정 종료 처리
  back-end/src/main/java/com/feedhanjum/back_end/core/config/ScheduleConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/core/domain/JobRecord.java
  back-end/src/main/java/com/feedhanjum/back_end/core/repository/JobRecordRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/infra/ScheduleEndScheduler.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/service/ScheduleServiceIntegrationTest.java
Labels: BE, feat

#133 [FD-318] 피드백 선호도 설정 화면 개발
  front-end/src/App.jsx
  front-end/src/api/useAuth.js
  front-end/src/api/useFeedback.js
  front-end/src/components/buttons/KeywordButton.jsx
  front-end/src/index.css
  front-end/src/mocks/handlers.js
  front-end/src/pages/feedback/FeedbackFavorite.jsx
Labels: FE, feat

#137 [FD-321] onSuccess 정상화
  front-end/src/api/useAuth.js
  front-end/src/api/useFeedback.js
  front-end/src/api/useFeedback2.js
  front-end/src/pages/feedback/FeedbackFavorite.jsx
  front-end/src/pages/feedback/FeedbackRequest.jsx
  front-end/src/pages/feedback/FeedbackSelf.jsx
Labels: FE, refactor

#132 [FD-317] feat: 존재하지 않은 경로 접근 시 404 응답하도록 변경
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/AuthInterceptor.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/FindControllerAdvice.java
Labels: BE, feat

#139 [FD-293] 피드백 리포트 조회
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FeedbackReportDto.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackCategory.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackFeeling.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackReport.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/ObjectiveFeedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/domain/FeedbackReportTest.java
Labels: BE, feat

#138 [FD-319] 팀 프로젝트 기간 변경 검증 로직 추가
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, feat

#143 [FD-210] 피드백 보내기 컴포넌트
  front-end/src/App.jsx
  front-end/src/api/useFeedback.js
  front-end/src/api/useFeedback2.js
  front-end/src/components/Accordion.jsx
  front-end/src/components/TextArea.jsx
  front-end/src/components/buttons/KeywordButton.jsx
  front-end/src/mocks/handlers.js
  front-end/src/mocks/mockData.js
  front-end/src/pages/feedback/FeedbackFavorite.jsx
  front-end/src/pages/feedback/FeedbackSend.jsx
  front-end/src/pages/feedback/FeedbackSendLayout.jsx
  front-end/src/pages/feedback/FeedbackSendStep.jsx
  front-end/src/pages/feedback/components/FeedbackSend1.jsx
  front-end/src/pages/feedback/components/FeedbackSend2.jsx
  front-end/src/pages/feedback/components/FeedbackSend3.jsx
  front-end/src/pages/feedback/components/ProgressBar.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/main/components/MainCard.jsx
Labels: FE, feat

#140 [FD-296] 팀 가입 시 일정에 해당 회원 추가 로직 구현
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/handler/AddScheduleMemberEventHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/TeamMemberJoinEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
Labels: BE, feat

#141 [FD-263] 팀 탈퇴 시 일정에 해당 회원 제거 로직 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/PasswordResetToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/SignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/handler/RemoveScheduleMemberEventHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleMemberRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/handler/TeamMemberLeftHandler.java
Labels: BE, feat

#142 [FD-322, FD-323] 피드백 선호도 선택지 조회 api 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/WebConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackRefinementController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/FeedbackPreference.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/handler/AddScheduleMemberEventHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/event/handler/RemoveScheduleMemberEventHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
Labels: BE, feat

#145 [FD-325] 회원가입 api 연결
  front-end/src/api/useAuth.js
  front-end/src/api/useFeedback.js
  front-end/src/api/useTeamspace.js
  front-end/src/components/Certification.jsx
  front-end/src/components/ProfileImage.jsx
  front-end/src/components/buttons/KeywordButton.jsx
  front-end/src/mocks/handlers.js
  front-end/src/mocks/handlers2.js
  front-end/src/pages/auth/SignUp.jsx
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/feedback/FeedbackFavorite.jsx
  front-end/src/pages/teamspace/TeamSpaceMakeSuccess.jsx
Labels: FE, feat

#149 [FD-327] 마이페이지 조회를 위한 회원 정보 조회 기능 추가
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/dto/LoginMemberDto.java
Labels: BE, feat

#148 [FD-82] 구글 로그인 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/GoogleAuthProperty.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/GoogleLoginRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/GoogleLoginResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/GoogleLoginUrlResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/GoogleSignupRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/SignupEmailVerifyRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/mapper/MemberMapper.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/EmailSignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/GoogleSignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/MemberDetails.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/PasswordChangeNotAllowedException.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/SessionConst.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/GoogleAuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/dto/GoogleLoginResultDto.java
  back-end/src/main/java/com/feedhanjum/back_end/core/config/RestClientConfig.java
  back-end/src/main/resources/application.yml
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/infra/AuthInterceptorTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/test/config/GoogleAuthMockConfig.java
  back-end/src/test/resources/application-test.yml
Labels: BE, feat

#147 [FD-179] 마이페이지 메인화면 구현
  front-end/src/App.jsx
  front-end/src/api/baseApi.js
  front-end/src/api/useAuth.js
  front-end/src/api/useMyPage.js
  front-end/src/components/Accordion.jsx
  front-end/src/mocks/handlers.js
  front-end/src/pages/feedback/FeedbackFavorite.jsx
  front-end/src/pages/feedback/FeedbackReceived.jsx
  front-end/src/pages/feedback/FeedbackSent.jsx
  front-end/src/pages/mypage/MyPageHome.jsx
  front-end/src/pages/mypage/SelfFeedback.jsx
  front-end/src/pages/teamspace/TeamSpaceList.jsx
Labels: FE, feat

#150 [FD-328] fix: 변수명 잘못된 문제 해결
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  vercel.json
Labels: BE, fix

#154 [FD-329] feat: cors 설정을 쉼표로 구분하는 링크 문자열로 받도록 설정
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/WebConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/property/CorsProperties.java
Labels: BE, chore

#155 [FD-300] 레디스 세션 적용
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/EmailSignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/GoogleSignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/PasswordResetToken.java
  back-end/src/main/java/com/feedhanjum/back_end/core/config/RedisConfig.java
  back-end/src/main/resources/application.yml
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
  back-end/src/test/resources/application-test.yml
Labels: BE, feat

#157 [FD-330] 회원가입 비밀번호 초기화 이메일 템플릿 적용
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/EmailService.java
  back-end/src/main/resources/templates/email.html
Labels: BE, feat

#158 [FD-333] 팀 스페이스 종료 날짜가 현재보다 미래가 되도록 수정
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/InAppNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/RetrospectControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/controller/InAppNotificationControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/service/ScheduleServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/domain/TeamTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/test/util/DomainTestUtils.java
Labels: BE, fix

#159 [FD-332] jpql에선 서브쿼리에서 limit이 지원되지 않는 문제 해결
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
Labels: BE, fix

#160 [FD-334] 피드백 발신자 수신자 value object로 리팩터링
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Receiver.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Sender.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/ReceivedFeedbackDto.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/SentFeedbackDto.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/ProfileImage.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepositoryTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/test/util/DomainTestUtils.java
Labels: BE, refactor

#165 [FD-339] order by를 적용한 쿼리가 fetch one을 사용한 문제 해결
  back-end/src/main/java/com/feedhanjum/back_end/member/controller/MemberController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/ScheduleQueryRepository.java
Labels: BE, fix

#167 [FD-340] 멤버 팀 일정 soft delete 구현
  back-end/src/main/java/com/feedhanjum/back_end/core/config/LoggingConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/main/resources/application.yml
Labels: BE, refactor

#168 [FD-338] 익명 피드백 도착 알림에서 보낸사람 이름을 익명처리
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackType.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FeedbackReceiveNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FeedbackReceiveNotification.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/domain/FeedbackReceiveNotificationTest.java
  back-end/src/test/java/com/feedhanjum/back_end/test/util/DomainTestUtils.java
Labels: BE, fix

#169 [FD-341] 구글 메일 이미지 깨짐
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/EmailService.java
  back-end/src/main/resources/static/logo.png
  back-end/src/main/resources/templates/email.html
Labels: BE, fix

#181 [FD-179] 마이페이지 로그아웃 기능추가
  front-end/src/App.jsx
  front-end/src/ProtectedRoute.jsx
  front-end/src/api/useAuth.js
  front-end/src/pages/feedback/FeedbackFavorite.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/mypage/MyPageHome.jsx
  front-end/src/pages/teamspace/TeamSpaceMake.jsx
  front-end/src/useBlockPop.jsx
Labels: FE, feat

#180 [FD-282] 피드백 리포트 생성됨 알림 발송
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FeedbackReceivedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/handler/FeedbackReceivedHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/infra/FeedbackReportCreateScheduler.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackCounterService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
Labels: BE, feat

#182 [FD-351] 웹푸시 구독정보 중복 값 없애기
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/WebPushSubscription.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/WebPushSubscriptionRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/WebPushService.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/service/WebPushServiceIntegrationTest.java
Labels: bug, BE

#189 [FD-350] 푸시알림 디버깅 1
  front-end/public/service-worker.js
  front-end/src/PushNotiManager.jsx
  front-end/src/api/usePushNoti.js
Labels: bug, FE

#188 [FD-355] 새로운 팀에 대한 api call이 필요없는 페이지에선 안하도록
  front-end/src/api/useMainPage.js
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/main/components/MainCard.jsx
  front-end/src/pages/teamspace/TeamSpaceList.jsx
  front-end/src/useTeam.jsx
Labels: FE, refactor

#191 [FD-357] 수시 피드백 요청 알림에 sender id 추가
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FrequentFeedbackRequestNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
Labels: BE, feat

#200 [FD-358] 메인화면 일정역할 추가기능 개선
  front-end/src/api/baseApi.js
  front-end/src/api/useCalendar.js
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
  front-end/src/pages/calendar/components/TodoAdd.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/main/components/MainCard.jsx
  front-end/src/utility/time.js
Labels: FE, fix

#202 [FD-360] 마이페이지 - 프로필 수정, 피드백 리포트 관련
  front-end/src/App.jsx
  front-end/src/api/useAuth.js
  front-end/src/api/useMyPage.js
  front-end/src/pages/feedback/FeedbackComplete.jsx
  front-end/src/pages/mypage/MyPageHome.jsx
  front-end/src/pages/mypage/ProfileEdit.jsx
  front-end/src/pages/mypage/Report.jsx
  front-end/src/pages/mypage/components/ReportKeywords.jsx
  front-end/src/pages/mypage/components/ReportResults.jsx
  front-end/src/pages/mypage/components/ReportTopKeywords.jsx
  front-end/src/type.js
Labels: FE, feat

#198 [FD-359] 수시 피드백 요청 중복 시 기존 요청 내용 업데이트 기능 추가
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/test/java/com/feedhanjum/back_end/team/domain/TeamTest.java
Labels: BE, fix

#201 [FD-364] 피드백 좋아요 알림의 수신, 발신자가 뒤바뀐 버그 수정
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/HeartReactionNotification.java
Labels: BE, fix

#204 [FD-365] 바텀시트 위치 조정
  front-end/src/Layout.jsx
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
  front-end/src/pages/calendar/components/TodoAdd.jsx
  front-end/src/pages/main/MainPage.jsx
Labels: FE, feat

#206 [FD-363] 미확인 알림 생성
  back-end/src/main/java/com/feedhanjum/back_end/core/domain/JobRecord.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/InAppNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/event/FeedbackReceiveNotificationUnreadEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/event/handler/FeedbackReceiveNotificationUnreadHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/infra/UnreadNotificationCheckScheduler.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/InAppNotificationQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/InAppNotificationRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/service/InAppNotificationServiceIntegrationTest.java
Labels: BE, feat

#203 [FD-306] ai 다듬기 아키텍처 구성
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/LoginMemberArgumentResolver.java
  back-end/src/main/java/com/feedhanjum/back_end/core/config/RedisConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/FeedbackRefinementController.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FeedbackRefineCountCompensationEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FeedbackSentEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/handler/FeedbackRefineCountCompensationHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/handler/FeedbackSentHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/AiRefineChanceAlreadyUsedException.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/ApiResponseFailException.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/exception/ExternalApiControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/infra/ChatGPTClient.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackRefineService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/dto/FeedbackRefineDto.java
  back-end/src/test/resources/application-test.yml
Labels: BE, feat

#205 [FD-366] 피드백 선호 변경 기능
  front-end/src/api/useFeedback.js
  front-end/src/pages/feedback/FeedbackFavorite.jsx
Labels: FE, feat

#207 [FD-370] 피드백 리포트 생성됨 알림에서 팀 이름 제거
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FeedbackReportCreatedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FeedbackReportCreateNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/FeedbackReportCreateNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/controller/InAppNotificationControllerTest.java
  back-end/src/test/resources/application-test.yml
Labels: BE, fix

#208 [FD-371] 피드백 요청 알림에 요청자 아이디 추가
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/FrequentFeedbackRequestNotificationDto.java
Labels: BE, fix

#209 [FD-348] 정기 피드백 요청을 전부 처리했을 경우, 다가오는 일정을 보여주도록 수정
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/RegularFeedbackRequestQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
Labels: BE, feat

#210 [FD-373] 종료된 팀에 가입 가능한 문제 수정
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamJoinToken.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamEndedException.java
  back-end/src/main/java/com/feedhanjum/back_end/team/exception/TeamMemberControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
Labels: BE, fix

#212 [FD-369] 팀 탈퇴 시 수신, 발신자로 설정된 정기, 수시 피드백 요청 삭제
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FrequentFeedbackRequestForApiRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/FrequentFeedbackRequestForApiResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/response/RegularFeedbackRequestForApiResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/handler/RemoveFeedbackRequestHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FrequentFeedbackRequestQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FrequentFeedbackRequestRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/RegularFeedbackRequestQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/RegularFeedbackRequestRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryService.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/repository/RegularFeedbackRequestRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/controller/FeedbackControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackQueryServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/test/util/DomainTestUtils.java
Labels: BE, feat

#214 [FD-30] 일정 삭제 로직 구현
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/ScheduleController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/dto/ScheduleRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Todo.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
Labels: BE, feat

#216 [FD-367] 새로운 미확인 알림 생성 로직
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/InAppNotification.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/InAppNotificationRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/test/java/com/feedhanjum/back_end/notification/service/InAppNotificationServiceIntegrationTest.java
Labels: BE, feat

#217 [FD-376] 피드백 요청 알림 중복 제거 및 업데이트
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/InAppNotificationQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
Labels: BE, feat

#218 [FD-380] 정기 피드백 요청 알림에 팀 이름 추가
  back-end/src/main/java/com/feedhanjum/back_end/notification/controller/dto/notification/RegularFeedbackRequestNotificationDto.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/domain/RegularFeedbackRequestNotification.java
Labels: BE, feat

#219 [FD-383] 일정 삭제 로직 버그 수정
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
Labels: BE, fix

#222 [FD-384] 뒤로가기 핸들링 커스텀 훅 생성
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/teamspace/TeamSpaceMake.jsx
  front-end/src/useHandlePop.jsx
Labels: FE, feat

#223 [FD-386] 수시 피드백 전송 시 연관 요청 삭제되도록 수정
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, fix

#227 [FD-377] 팀스페이스 종료일 버그 수정
  front-end/src/utility/time.js
Labels: FE, fix

#229 [FD-388] 팀 정보 수정과 일정 생성 간 동시성 문제 해결
  back-end/src/main/java/com/feedhanjum/back_end/schedule/controller/ScheduleController.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamCreateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/dto/TeamUpdateRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/main/java/com/feedhanjum/back_end/teamplanorchestration/service/TeamPlanOrchestrationService.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/controller/ScheduleControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/schedule/service/ScheduleServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/team/service/TeamServiceTest.java
  back-end/src/test/java/com/feedhanjum/back_end/teamplanorchestration/service/TeamPlanOrchestrationServiceTest.java
Labels: BE, feat

#231 [FD-397] feat: 프로메테우스 구현 마이크로미터 라이브러리 추가
  back-end/build.gradle
Labels: BE, feat

#228 [FD-391] iOS 푸시알림
  front-end/public/service-worker.js
  front-end/src/App.jsx
  front-end/src/PushNotiManager.jsx
  front-end/src/api/usePushNoti.js
  front-end/src/components/Accordion.jsx
  front-end/src/main.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/pages/main/components/OnboardingNotice.jsx
  front-end/src/pages/teamspace/TeamSpaceMake.jsx
  front-end/src/pages/teamspace/TeamSpaceMakeSuccess.jsx
Labels: FE, feat

#233 [FD-356] 받은 피드백, 보낸 피드백, 나의 회고 화면 한 파일로 통일
  front-end/src/App.jsx
  front-end/src/pages/feedback/FeedbackHistory.jsx
  front-end/src/pages/feedback/FeedbackSent.jsx
  front-end/src/pages/feedback/components/FeedBack.jsx
  front-end/src/pages/mypage/SelfFeedback.jsx
Labels: FE, refactor

#232 [FD-396] 이메일가입, 비밀번호 초기화, 구글 가입 토큰 세션 -> 레디스 리팩터링
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/EmailSignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/GoogleSignupToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/PasswordResetToken.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/LoginMemberArgumentResolver.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/SessionConst.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/EmailSignupTokenService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/GoogleSignupTokenService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/PasswordResetTokenService.java
  back-end/src/main/java/com/feedhanjum/back_end/core/config/RedisConfig.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
Labels: BE, refactor

#235 [FD-399] 팀스페이스 디버깅
  front-end/src/pages/teamspace/TeamSpaceEdit.jsx
  front-end/src/pages/teamspace/TeamSpaceList.jsx
  front-end/src/pages/teamspace/TeamSpaceManage.jsx
  front-end/src/pages/teamspace/components/MemberElement.jsx
  front-end/src/utility/inputChecker.js
Labels: FE, fix

#242 [FD-403] 일정 디버깅
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
  front-end/src/pages/calendar/components/ScheduleCard.jsx
  front-end/src/pages/main/MainPage.jsx
  front-end/src/utility/time.js
Labels: FE, fix

#243 [FD-411] 일정 validation 디버깅
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
  front-end/src/pages/calendar/components/Todo.jsx
  front-end/src/utility/inputChecker.js
Labels: FE, feat

#244 [FD-412] 구글계정 팀가입
  front-end/index.html
  front-end/src/api/useAuth.js
  front-end/src/index.css
  front-end/src/pages/auth/Splash.jsx
  front-end/src/pages/auth/SplashForOAuth.jsx
Labels: FE, feat

#245 [FD-399] 팀스페이스 디버깅 (이었던것)
  front-end/src/pages/main/NotificationPage.jsx
  front-end/src/pages/main/components/Alarm.jsx
Labels: FE, feat, fix

#247 [FD-413] 메인페이지와 일정페이지에서 일정 추가/수정시 날짜 바꾸면 내용 초기화되던 버그 수정
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
Labels: FE, fix

#238 [FD-404] 주관식 피드백 없이 피드백을 보낼 수 없는 버그 수정
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/FrequentFeedbackSendRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/controller/dto/request/RegularFeedbackSendRequest.java
Labels: BE, fix

#250 [FD-413] 일부 일정 흰화면 나오는 버그 디버깅
  front-end/src/pages/calendar/components/ScheduleCard.jsx
Labels: FE, fix

#252 [FD-356] 피드백 중복조회 디버깅
  front-end/src/api/useFeedback.js
  front-end/src/api/useMyPage.js
  front-end/src/components/Spinner.jsx
  front-end/src/components/TextArea.jsx
  front-end/src/pages/calendar/Calendar.jsx
  front-end/src/pages/calendar/components/CalendarParts.jsx
  front-end/src/pages/calendar/components/CalendarWeeks.jsx
  front-end/src/pages/feedback/FeedbackHistory.jsx
  front-end/src/pages/main/NotificationPage.jsx
Labels: FE, feat, fix

#253 [FD-415] onClick 콜백 분리
  front-end/src/components/MainCard2.jsx
  front-end/src/pages/auth/SignUp.jsx
  front-end/src/pages/calendar/components/ScheduleAction.jsx
  front-end/src/pages/calendar/components/Todo.jsx
  front-end/src/pages/feedback/FeedbackHistory.jsx
  front-end/src/pages/feedback/FeedbackSendFreq.jsx
  front-end/src/pages/feedback/components/FeedBack.jsx
  front-end/src/pages/main/NotificationPage.jsx
  front-end/src/pages/main/components/OnboardingNotice.jsx
  front-end/src/pages/teamspace/TeamSpaceEdit.jsx
  front-end/src/pages/teamspace/TeamSpaceMakeSuccess.jsx
  front-end/src/pages/teamspace/TeamSpaceManage.jsx
  front-end/src/pages/teamspace/components/MemberElement.jsx
Labels: FE, refactor

#255 [FD-409] 모달 관련 개선 및 버그 수정
  front-end/src/App.jsx
  front-end/src/assets/images/box.webp
  front-end/src/assets/images/file.webp
  front-end/src/assets/images/letter.webp
  front-end/src/components/NavBar.jsx
  front-end/src/components/modals/ModalBase.jsx
  front-end/src/pages/auth/PasswordReset.jsx
  front-end/src/pages/auth/SignIn.jsx
  front-end/src/pages/auth/SignUp.jsx
  front-end/src/pages/auth/components/AuthHeader.jsx
  front-end/src/pages/feedback/FeedbackFavorite.jsx
  front-end/src/pages/feedback/FeedbackHistory.jsx
  front-end/src/pages/feedback/FeedbackRequest.jsx
  front-end/src/pages/feedback/FeedbackSelf.jsx
  front-end/src/pages/feedback/FeedbackSendLayout.jsx
  front-end/src/pages/main/NotificationPage.jsx
  front-end/src/pages/main/components/Banner.jsx
  front-end/src/pages/mypage/MyPageHome.jsx
  front-end/src/pages/mypage/ProfileEdit.jsx
  front-end/src/pages/mypage/Report.jsx
  front-end/src/pages/teamspace/TeamSpaceEdit.jsx
  front-end/src/pages/teamspace/TeamSpaceList.jsx
  front-end/src/pages/teamspace/TeamSpaceMake.jsx
  front-end/src/pages/teamspace/TeamSpaceMakeSuccess.jsx
  front-end/src/pages/teamspace/TeamSpaceManage.jsx
  front-end/src/styles/index.css
  front-end/src/utility/handleModal.js
Labels: FE, fix

#251 [FD-414] 미확인 피드백이 2개 이상 존재할 때 추가 생성 불가능 버그 수정
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/property/GoogleAuthProperties.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/GoogleAuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/InAppNotificationQueryRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/repository/InAppNotificationRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/notification/service/InAppNotificationService.java
  back-end/src/test/java/com/feedhanjum/back_end/test/config/GoogleAuthMockConfig.java
Labels: BE, fix

#256 [FD-420] 샘플 피드백 보내는 페이지 추가
  back-end/src/main/resources/static/index.html
  back-end/src/main/resources/static/qrcode.html
Labels: BE, chore

#259 [FD-419] docs: 백엔드 README.md 작성
  README.md
  docs/backend_architecture.png
  docs/ci_cd_workflow.png
  docs/domain_model.jpg
  docs/domain_model.png
  docs/frontend_architecture.png
  docs/도메인 모델.drawio
Labels: documentation, BE

#260 [FD-422] 이메일 타입이 아닌 계정에 대한 비밀번호 초기화 방지 로직 추가
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
Labels: BE, fix

#261 [FD-424] 팀 가입 API 응답으로 가입한 팀 정보 반환
  back-end/src/main/java/com/feedhanjum/back_end/team/controller/TeamController.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamJoinToken.java
  back-end/src/main/java/com/feedhanjum/back_end/team/service/TeamService.java
  back-end/src/test/java/com/feedhanjum/back_end/team/controller/TeamControllerIntegrationTest.java
Labels: BE, feat

#262 [FD-423] fix: DTO Projection 후 애플리케이션 조인 시 중복된 역할이 생기는 문제 수정
  back-end/src/main/java/com/feedhanjum/back_end/schedule/service/ScheduleService.java
Labels: BE, fix

#267 [FD-427] README.md 업데이트
  README.md
  docs/frontend_architecture.png
Labels: documentation

#270 [FD-430] 에러페이지 개선
  front-end/src/App.jsx
  front-end/src/components/ErrorFallBack.jsx
  front-end/src/components/Layout.jsx
Labels: FE, feat, refactor

#266 [FD-426] Google 로그인 URL 생성 시 동적 redirect URI 지원 추가
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/GoogleAuthService.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
Labels: BE, feat

#273 docs: README.md 링크 수정
  README.md
Labels: documentation

#271 [FD-429] team plan orchestrator 생성
  back-end/src/main/java/com/feedhanjum/back_end/teamplanorchestration/domain/TeamPlanOrchestrator.java
  back-end/src/main/java/com/feedhanjum/back_end/teamplanorchestration/service/TeamPlanOrchestrationService.java
  back-end/src/test/java/com/feedhanjum/back_end/teamplanorchestration/service/TeamPlanOrchestrationServiceTest.java
Labels: BE, refactor

#272 [FD-421] non unique result exception lock timeout exception 503 핸들링
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/InternalErrorControllerAdvice.java
Labels: BE, feat

#276 [FD-432] TeamPlanOrchestrationService 공유 잠금과 배타 잠금 구분해서 사용하도록 변경
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/InternalErrorControllerAdvice.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/teamplanorchestration/service/TeamPlanOrchestrationService.java
  back-end/src/test/java/com/feedhanjum/back_end/teamplanorchestration/service/TeamPlanOrchestrationServiceTest.java
Labels: BE, feat

#282 [FD-435] 마지막 세가지 수정
  front-end/src/components/TeamMatesCard.jsx
  front-end/src/components/buttons/MediumButton.jsx
  front-end/src/pages/main/components/Banner.jsx
Labels: FE, fix
