Repository softeer5th/Team5-EQUUS-N, pull requests merged in 2025-01, with the labels that each got.

#2 [FD-158] chore: 백엔드 프로젝트 생성
  feed-hanjum-backend/.gitattributes
  feed-hanjum-backend/.gitignore
  feed-hanjum-backend/build.gradle
  feed-hanjum-backend/gradle/wrapper/gradle-wrapper.jar
  feed-hanjum-backend/gradle/wrapper/gradle-wrapper.properties
  feed-hanjum-backend/gradlew
  feed-hanjum-backend/gradlew.bat
  feed-hanjum-backend/settings.gradle
  feed-hanjum-backend/src/main/java/com/feedhanjum/feed_hanjum_backend/FeedHanjumBackendApplication.java
  feed-hanjum-backend/src/main/resources/application.properties
  feed-hanjum-backend/src/test/java/com/feedhanjum/feed_hanjum_backend/FeedHanjumBackendApplicationTests.java
Labels: BE, chore

#4 [FD-169] docs: 도메인 모델 작성
  README.md
  docs/domain_model.jpg
  docs/도메인 모델.drawio
Labels: documentation

#8 [FD-161] docs: 사용자 인증 기능 분석
  docs/사용자 인증/사용자 인증 SD.drawio
Labels: documentation

#9 [FD-162] docs: 사용자 프로필 관리 기능 유즈케이스 시퀀스 다이어그램 추가
  docs/사용자 프로필 관리/사용자 프로필 관리 SD.drawio
Labels: documentation

#10 [FD-163] docs: 팀 관리 유즈케이스 시퀀스 다이어그램 추가
  docs/팀 관리/팀 관리 SD.drawio
Labels: documentation

#12 [FD-218] chore: 패키지 이름 변경
  back-end/.gitattributes
  back-end/.gitignore
  back-end/build.gradle
  back-end/gradle/wrapper/gradle-wrapper.jar
  back-end/gradle/wrapper/gradle-wrapper.properties
  back-end/gradlew
  back-end/gradlew.bat
  back-end/settings.gradle
  back-end/src/main/java/com/feedhanjum/back_end/BackEndApplication.java
  back-end/src/main/resources/application.properties
  back-end/src/test/java/com/feedhanjum/back_end/BackEndApplicationTests.java
  feed-hanjum-backend/settings.gradle
  feed-hanjum-backend/src/main/resources/application.properties
Labels: BE, chore

#13 Fd 219 개발 운영 환경별 설정파일 분리
  back-end/.gitignore
  back-end/src/main/resources/application-dev.yml
  back-end/src/main/resources/application.properties
  back-end/src/main/resources/application.yml
Labels: BE, chore

#11 [FD-164] docs: 일정 관리 유즈케이스 시퀀스 다이어그램 추가
  docs/일정 관리/일정 관리 SD.drawio
Labels: documentation

#17 [FD-220] build: swagger 의존성 및 기본 설정추가
  back-end/build.gradle
  back-end/src/main/resources/application.yml
Labels: BE, chore

#18 [FD-221] feat: 핵심 도메인 구현
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/FeedbackType.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Retrospect.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleRole.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/TeamMember.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/TeamRole.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Todo.java
  docs/도메인 모델.drawio
Labels: BE, feat

#20 [FD-221] fix: 사용하지 않는 코드 제거, 접근 제어자 수정, 버그 수정
  back-end/src/main/java/com/feedhanjum/back_end/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/TeamMember.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/TeamRole.java
  back-end/src/main/java/com/feedhanjum/back_end/domain/Todo.java
  docs/도메인 모델.drawio
Labels: BE, fix

#23 [FD-100] feat: 회고 작성하기
  back-end/src/main/java/com/feedhanjum/back_end/domain/ScheduleRole.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackType.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Retrospect.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/RetrospectRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
  back-end/src/main/java/com/feedhanjum/back_end/member/domain/Member.java
  back-end/src/main/java/com/feedhanjum/back_end/member/repository/MemberRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Schedule.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleRole.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/Todo.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/Team.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamRole.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java
Labels: BE, feat

#22 [FD-226] refactor: 도메인 별 패키지 분리
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/RegularFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/schedule/domain/ScheduleMember.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/TeamMember.java
Labels: BE

#19 [FD-255] 아이콘 관련 수정 사항들
  front-end/src/assets/Icons/calendar.svg
  front-end/src/assets/Icons/check.svg
  front-end/src/assets/Icons/check_box/noneclick.svg
  front-end/src/assets/Icons/check_box/onclick.svg
  front-end/src/assets/Icons/chevron_left.svg
  front-end/src/assets/Icons/crown.svg
  front-end/src/assets/Icons/delete.svg
  front-end/src/assets/Icons/delete_small.svg
  front-end/src/assets/Icons/heart/activate.svg
  front-end/src/assets/Icons/heart/default.svg
  front-end/src/assets/Icons/logout.svg
  front-end/src/assets/Icons/plus_m.svg
  front-end/src/assets/Icons/plus_s.svg
  front-end/src/assets/Icons/send.svg
  front-end/src/components/Icon.jsx
  front-end/src/components/buttons/TextButton.jsx
Labels: FE, fix

#21 Fd 201 날짜관련 컴포넌트 개발
  front-end/src/App3.jsx
  front-end/src/components/Calendar.jsx
  front-end/src/components/CalendarParts.jsx
  front-end/src/components/ProfileImage.jsx
  front-end/src/utility/time.js
Labels: FE, feat

#24 Fd 190 스케줄카드 컴포넌트 개발
  front-end/src/assets/Icons/chevron_down.svg
  front-end/src/assets/Icons/chevron_up.svg
  front-end/src/components/ScheduleCard.jsx
  front-end/src/components/buttons/MediumButton.jsx
Labels: FE, feat

#27 [FD-101] feat: 회고 조회하기
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/RetrospectRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/RetrospectService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/RetrospectServiceTest.java
Labels: BE, feat

#26 [FD-193] 피드백 컴포넌트 개발
  front-end/src/components/FeedBack.jsx
  front-end/src/components/ProfileImage.jsx
Labels: FE, feat

#29 [FD-6] feat: 회원가입 기능 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/MemberSignupResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/mapper/MemberMapper.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/domain/MemberDetails.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthExceptionHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/EmailAlreadyExistsException.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/repository/MemberDetailsRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/main/java/com/feedhanjum/back_end/core/exception/ValidationControllerAdvice.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
Labels: BE, feat

#30 [FD-7] feat: 로그인 기능 구현
  back-end/build.gradle
  back-end/src/main/java/com/feedhanjum/back_end/auth/config/AuthConfig.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/dto/LoginResponse.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/AuthExceptionHandler.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/exception/InvalidCredentialsException.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/infra/SessionConst.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/passwordencoder/BCryptPasswordEncoder.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/passwordencoder/PasswordEncoder.java
  back-end/src/main/java/com/feedhanjum/back_end/auth/service/AuthService.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/service/AuthServiceTest.java
Labels: BE, feat

#32 [FD-10] feat: 로그아웃 구현
  back-end/src/main/java/com/feedhanjum/back_end/auth/controller/AuthController.java
  back-end/src/test/java/com/feedhanjum/back_end/auth/controller/AuthControllerTest.java
Labels: BE, feat

#28 [FD-37] feat: 수시 피드백 전송
  back-end/src/main/java/com/feedhanjum/back_end/event/EventPublisher.java
  back-end/src/main/java/com/feedhanjum/back_end/event/SpringEventPublisherImpl.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/Feedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/FeedbackCategory.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/domain/ObjectiveFeedback.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/event/FrequentFeedbackCreatedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/repository/FeedbackRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat

#34 [FD-187] 공통 컴포넌트 개발
  front-end/src/components/Alarm.jsx
  front-end/src/components/Calendar.jsx
  front-end/src/components/CalendarParts.jsx
  front-end/src/components/FeedBack.jsx
  front-end/src/components/MainCard2.jsx
  front-end/src/components/MemberElement.jsx
  front-end/src/components/NavBar2.jsx
  front-end/src/components/ProfileImage.jsx
  front-end/src/components/ScheduleCard.jsx
  front-end/src/components/TeamElement.jsx
  front-end/src/components/Toast.jsx
  front-end/src/components/buttons/FeedBackButton.jsx
  front-end/src/components/buttons/LargeButton.jsx
  front-end/src/components/buttons/MediumButton.jsx
  front-end/src/components/buttons/SmallButton.jsx
  front-end/src/utility/time.js
Labels: FE, chore

#33 [FD-202] 인풋 관련 컴포넌트 개발
  front-end/src/App3.jsx
  front-end/src/assets/Icons/eye.svg
  front-end/src/components/Certification.jsx
  front-end/src/components/CustomInput.jsx
  front-end/src/components/Icon.jsx
  front-end/src/components/buttons/SmallButton.jsx
Labels: FE, feat

#36 [FD-200] 네비바, 아코디언, 프로그래스바, 리포트 컴포넌트 개발
  front-end/src/App2.jsx
  front-end/src/assets/Icons/delete.svg
  front-end/src/assets/Icons/logo.svg
  front-end/src/components/Accordion.jsx
  front-end/src/components/Icon.jsx
  front-end/src/components/ReportKeywords.jsx
  front-end/src/components/ReportResults.jsx
  front-end/src/components/Tag.jsx
  front-end/src/components/buttons/TextButton.jsx
  front-end/src/components/progressBar.jsx
  front-end/src/index.css
Labels: FE, feat

#37 [FD-237] fix: AuthInterceptor 버그 수정
  back-end/src/test/java/com/feedhanjum/back_end/auth/infra/AuthInterceptorTest.java
Labels: BE, fix

#39 [FD-240] 프론트 폴더 세팅
  front-end/src/App3.jsx
  front-end/src/pages/calendar/components/Calendar.jsx
  front-end/src/pages/calendar/components/CalendarParts.jsx
  front-end/src/pages/calendar/components/ScheduleCard.jsx
  front-end/src/pages/feedback/components/FeedBack.jsx
  front-end/src/pages/feedback/components/ProgressBar.jsx
  front-end/src/pages/main/components/Alarm.jsx
  front-end/src/pages/mypage/components/ReportKeywords.jsx
  front-end/src/pages/mypage/components/ReportResults.jsx
  front-end/src/pages/teamspace/components/MemberElement.jsx
  front-end/src/pages/teamspace/components/TeamElement.jsx
Labels: FE, chore

#38 [FD-238] build: pull request 생성 시 테스트 실행시키는 GitHub action 만들기
  .github/workflows/gradle-test.yml
Labels: BE, chore

#35 [FD-36] feat:수시 피드백 요청
  back-end/src/main/java/com/feedhanjum/back_end/feedback/service/FeedbackService.java
  back-end/src/main/java/com/feedhanjum/back_end/team/domain/FrequentFeedbackRequest.java
  back-end/src/main/java/com/feedhanjum/back_end/team/event/FrequentFeedbackRequestCreatedEvent.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/FrequentFeedbackRequestRepository.java
  back-end/src/main/java/com/feedhanjum/back_end/team/repository/TeamMemberRepository.java
  back-end/src/test/java/com/feedhanjum/back_end/feedback/service/FeedbackServiceTest.java
Labels: BE, feat
